name: Fetch News (daily)

on:
  schedule:
    - cron: '0 3 * * *' # JST 12:00 (approx) adjust as needed
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Fetch news and build JSON
        run: node scripts/fetch_news.mjs

      - name: Commit and push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add data/news.json
            git commit -m "chore(data): update news.json (scheduled)"
            git push
          else
            echo "No changes"
          fi
